//! Builds the full Lua API surface listing (lua_api.txt) from source scripts and UI bytecode.
use crate::{luac, luascan, pack};
use std::collections::{BTreeMap, BTreeSet};

const STDLIB: &[&str] = &["print", "require", "tostring", "tonumber", "pairs", "ipairs", "assert", "error", "type", "unpack", "select", "module",
    "setmetatable", "getmetatable", "pcall", "xpcall", "next", "rawget", "rawset", "loadstring", "dofile", "collectgarbage", "setfenv", "getfenv", "loadfile", "load"];
const STDMODS: &[&str] = &["math", "string", "table", "os", "debug", "io", "package", "coroutine"];

type Entry = (usize, BTreeMap<usize, usize>, BTreeSet<String>);

fn line(name: &str, e: &Entry) -> String {
    let acs: Vec<String> = e.1.iter().map(|(a, n)| format!("{}:{}", a, n)).collect();
    format!("{:<58} calls={:<5} argc{{{}}} files={}", name, e.0, acs.join(","), e.2.len())
}

pub fn run(_a: &[String]) {
    let srcs = luascan::gather_sources();
    let mut camp = luascan::Agg::default(); // campaign-side: loose campaign scripts + episodicscripting + export_*
    let mut batt = luascan::Agg::default(); // battle scripts + scripting_library*
    let mut all = luascan::Agg::default();
    let mut files_lua = 0;
    for (n, s) in &srcs {
        if n.starts_with("sound.pack") { continue; }
        files_lua += 1;
        luascan::scan(s, n, &mut all);
        if n.contains(".battle_script") || n.contains("scripting_library") || n.contains("battle_scripted") { luascan::scan(s, n, &mut batt); } else { luascan::scan(s, n, &mut camp); }
    }
    let defined: BTreeSet<String> = all.defined_funcs.keys().map(|k| k.rsplit(['.', ':']).next().unwrap_or(k).to_string()).collect();

    println!("# Napoleon: Total War Lua API surface (generated by worker3 campaign_tools `lua-api`).");
    println!("# Sources scanned: {} Lua source files (loose campaign scripting.lua x8, all_scripted.lua, battle_scripted.lua,", files_lua);
    println!("#   data.pack root *.lua x10, *.battle_script x24) + 497 compiled UI .luac files (data.pack ui\\**).");
    println!("# 'calls' = number of call sites; argc{{n:count}} = histogram of argument counts at call sites (source only).");
    println!("# Receivers shown as written; method calls on expression results are '<expr>:name'. Heuristic tokeniser: INFERRED.");
    println!();

    let sections: &[(&str, &dyn Fn(&str) -> Option<String>)] = &[
        ("CAMPAIGN GAME INTERFACE  (scripting.game_interface:X / game_interface:X ; object created by GAME(context) on NewSession)", &|k: &str| k.strip_prefix("scripting.game_interface:").or_else(|| k.strip_prefix("game_interface:")).map(|s| s.to_string())),
        ("CONDITIONS  (conditions.X(..., context) - engine-provided predicate table)", &|k: &str| k.strip_prefix("conditions.").map(|s| s.to_string())),
        ("EFFECT  (effect.X - engine-provided action table)", &|k: &str| k.strip_prefix("effect.").map(|s| s.to_string())),
        ("CAMPAIGN UI  (CampaignUI.X)", &|k: &str| k.strip_prefix("CampaignUI.").map(|s| s.to_string())),
        ("EPISODIC SCRIPTING MODULE  (scripting.X, Lua-defined in data.pack episodicscripting.lua)", &|k: &str| if k.starts_with("scripting.") && !k.starts_with("scripting.game_interface") { Some(k[10..].to_string()) } else { None }),
        ("LOGGING  (out.X)", &|k: &str| k.strip_prefix("out.").map(|s| s.to_string())),
    ];
    for (title, f) in sections {
        println!("== {} [campaign-side scripts]", title);
        let mut n = 0;
        let mut merged: BTreeMap<String, Entry> = BTreeMap::new();
        for (k, e) in &camp.calls { if let Some(m) = f(k) { let t = merged.entry(m).or_default(); t.0 += e.0; for (a, c) in &e.1 { *t.1.entry(*a).or_default() += c; } for x in &e.2 { t.2.insert(x.clone()); } } }
        for (m, e) in &merged { println!("  {}", line(m, e)); n += 1; }
        println!("  ({} distinct)\n", n);
    }
    // Battle: battle:X
    println!("== BATTLE OBJECT  (battle:X where battle = empire_battle:new()) [battle scripts]");
    let mut n = 0;
    for (k, e) in &batt.calls { if let Some(m) = k.strip_prefix("battle:") { println!("  {}", line(m, e)); n += 1; } }
    println!("  ({} distinct)\n", n);
    for (title, agg) in [("BATTLE SCRIPTS", &batt), ("CAMPAIGN-SIDE SCRIPTS", &camp)] {
        println!("== METHODS CALLED ON OTHER OBJECTS ({}) - aggregated by method name; example receivers", title);
        let mut by: BTreeMap<String, (usize, BTreeSet<String>)> = BTreeMap::new();
        for (k, e) in &agg.calls {
            if k.starts_with("scripting.game_interface:") || k.starts_with("game_interface:") || k.starts_with("battle:") { continue; }
            if let Some(p) = k.rfind(':') { let m = &k[p + 1..]; let ent = by.entry(m.to_string()).or_default(); ent.0 += e.0; if ent.1.len() < 3 { ent.1.insert(k[..p].to_string()); } }
        }
        for (m, (c, r)) in &by { println!("  {:<46} calls={:<5} e.g. {}", m, c, r.iter().cloned().collect::<Vec<_>>().join(", ")); }
        println!("  ({} distinct)\n", by.len());
    }
    println!("== GLOBAL FUNCTIONS CALLED BUT NOT DEFINED IN ANY SCANNED SCRIPT (engine globals; Lua stdlib excluded)");
    for (k, e) in &all.calls { if !k.contains(['.', ':']) && !defined.contains(k) && !STDLIB.contains(&k.as_str()) { println!("  {}", line(k, e)); } }
    println!();
    println!("== OTHER DOTTED CALLS (root not a Lua std module; may be Lua-defined tables) with >=2 call sites");
    for (k, e) in &all.calls {
        if let Some(p) = k.find('.') { let root = &k[..p]; if k.contains(':') || STDMODS.contains(&root) || ["conditions", "effect", "CampaignUI", "scripting", "out"].contains(&root) { continue; }
            if e.0 >= 2 { println!("  {}", line(k, e)); } }
    }
    println!();
    println!("== CONTEXT FIELDS READ (context.X)");
    for (k, c) in &all.context_fields { println!("  {:<40} {}", k, c); }
    println!();
    // events
    let ev_src = pack::Pack::open(pack::data_path("data.pack")).ok().and_then(|p| p.find("events.lua").cloned().map(|e| p.read(&e).unwrap())).unwrap_or_default();
    let ev_text = String::from_utf8_lossy(&ev_src);
    let mut declared: BTreeSet<String> = BTreeSet::new();
    for l in ev_text.lines() { let l = l.trim(); if let Some(nm) = l.strip_suffix("= {}") { let nm = nm.trim(); if nm.len() > 1 { declared.insert(nm.to_string()); } } }
    println!("== EVENTS: declared in data.pack events.lua ({} unique names) / registrations in scripts (AddEventCallBack + events.X[#events.X+1])", declared.len());
    let mut all_ev: BTreeSet<String> = declared.clone();
    for k in all.events.keys() { all_ev.insert(k.clone()); }
    let mut lc = luac::Agg::default();
    let p = pack::Pack::open(pack::data_path("data.pack")).unwrap();
    for e in &p.entries { if e.path.to_ascii_lowercase().ends_with(".luac") { let b = p.read(e).unwrap(); if let Ok((_, pr)) = luac::parse(&b) { luac_walk(&pr, &e.path, &mut lc); } } }
    for k in lc.events.keys() { all_ev.insert(k.clone()); }
    for ev in &all_ev {
        let reg = all.events.get(ev).map(|x| x.0).unwrap_or(0);
        let ui = lc.events.get(ev).copied().unwrap_or(0);
        println!("  {:<44} declared={} script_registrations={:<3} luac_refs={}", ev, if declared.contains(ev) { "Y" } else { "N" }, reg, ui);
    }
    println!();
    println!("== UI BYTECODE (.luac) GLOBALS REFERENCED (GETGLOBAL)");
    for (k, c) in &lc.globals { println!("  {:<44} {}", k, c); }
    println!();
    println!("== UI BYTECODE (.luac) CALL TARGETS (register-tracked; '?' = unknown receiver) with >=1 site");
    let mut by: BTreeMap<String, usize> = BTreeMap::new();
    for (k, (c, _)) in &lc.calls { let key = if k.starts_with('?') || k.starts_with("?:") { k.clone() } else { k.clone() }; *by.entry(key).or_default() += c; }
    for (k, c) in &by { println!("  {:<60} {}", k, c); }
}

fn luac_walk(p: &luac::Proto, f: &str, agg: &mut luac::Agg) { luac::walk_pub(p, f, agg); }
